stages:
  preprocess:
    cmd: python recommendation-service/src/preprocess.py
    deps:
      - recommendation-service/data/loans.csv
      - recommendation-service/src/preprocess.py
    outs:
      - recommendation-service/data/loans_clean.csv

  train:
    cmd: python recommendation-service/src/train.py
    deps:
      - recommendation-service/data/loans_clean.csv
      - recommendation-service/src/train.py
    outs:
      - recommendation-service/model/model.pkl

  evaluate:
    cmd: python recommendation-service/src/evaluate.py
    deps:
      - recommendation-service/model/model.pkl
      - recommendation-service/src/evaluate.py
    metrics:
      - recommendation-service/model/metrics.json