stages:

  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/loans.csv
    outs:
      - data/loans_clean.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/loans_clean.csv
    outs:
      - model/model.pkl

  evaluate:
    cmd: python evaluate.py
    deps:
      - evaluate.py
      - model/model.pkl
    metrics:
      - metrics.json